export const facilityOptions = [
    { title: "elevator" },
    { title: "hotTub" },
    { title: "pool" },
    { title: "indoorFireplace" },
    { title: "dryer" },
    { title: "gym" },
    { title: "kitchen" },
    { title: "wifi" },
    { title: "heating" },
    { title: "cableTV" },
];

export const columns = [
    {
        id: 1,
        name: "name",
        label: "Room",
        type: "text",
        placeholder: "High Standard Room",
    },
    {
        id: 2,
        name: "price",
        label: "Price",
        type: "number",
        placeholder: "$100.000",
    },
    {
        id: 3,
        name: "guests",
        label: "Guests",
        type: "number",
        placeholder: "7",
    },
    {
        id: 4,
        name: "bedRoom",
        label: "Bedroom",
        type: "number",
        placeholder: "7",
    },
    {
        id: 5,
        name: "bath",
        label: "Bath",
        type: "number",
        placeholder: "7",
    },
    {
        id: 6,
        name: "description",
        label: "Description",
        type: "text",
        placeholder: "Write some cool description to the room",
    },
    {
        id: 7,
        name: "facilities",
        label: "Facilities",
        type: "multi-autocomplete",
        options: facilityOptions,
        placeholder: "Facilities",
    },
];
