export const columns = [
    {
        id: 1,
        name: "name",
        label: "Room",
        type: "text",
        placeholder: "High Standard Room",
    },
    {
        id: 2,
        name: "price",
        label: "Price",
        type: "number",
        placeholder: "$100.000",
    },
    {
        id: 3,
        name: "guests",
        label: "Guests",
        type: "number",
        placeholder: "7",
    },
    {
        id: 4,
        name: "bedRoom",
        label: "Bedroom",
        type: "number",
        placeholder: "7",
    },
    {
        id: 5,
        name: "bath",
        label: "Bath",
        type: "number",
        placeholder: "7",
    },
    {
        id: 6,
        name: "description",
        label: "Description",
        type: "text",
        placeholder: "Write some cool description to the room",
    },
    {
        id: 7,
        name: "facilities",
        label: "Facilities",
        type: "multi-autocomplete",
        options: [
            { title: "elevator", value: false },
            { title: "hotTub", value: false },
            { title: "pool", value: false },
            { title: "indoorFireplace", value: false },
            { title: "dryer", value: false },
            { title: "gym", value: false },
            { title: "kitchen", value: false },
            { title: "wifi", value: false },
            { title: "heating", value: false },
            { title: "cableTV", value: false },
        ],
        placeholder: "Facilities",
    },
];
