export const facilityOptions = [
    { title: "mayGiat" },
    { title: "banLa" },
    { title: "tivi" },
    { title: "dieuHoa" },
    { title: "wifi" },
    { title: "bep" },
    { title: "doXe" },
    { title: "hoBoi" },
    { title: "banUi" },
    // { title: "tivi" },
];

export const formColumns = [
    {
        id: 1,
        name: "tenPhong",
        label: "Room",
        type: "text",
        placeholder: "High Standard Room",
    },
    {
        id: 2,
        name: "giaTien",
        label: "Price",
        type: "number",
        placeholder: "$100.000",
    },
    {
        id: 3,
        name: "khach",
        label: "Guests",
        type: "number",
        placeholder: "7",
    },
    {
        id: 4,
        name: "phongNgu",
        label: "Bedroom",
        type: "number",
        placeholder: "7",
    },
    {
        id: 5,
        name: "phongTam",
        label: "Bath",
        type: "number",
        placeholder: "7",
    },
    {
        id: 6,
        name: "moTa",
        label: "Description",
        type: "text",
        multiline: true,
        placeholder: "Write some cool description to the room",
    },
    {
        id: 7,
        name: "facilities",
        label: "Facilities",
        type: "multi-autocomplete",
        options: facilityOptions,
        placeholder: "Facilities",
    },
];
