const nearPlaceList = [
    {
        deleteAt: false,
        _id: 6,
        name: "Hai Chau",
        province: "Thành phố Đà Nẵng",
        country: "Việt Nam",
        valueate: 10,
        __v: 0,
        image: "https://static.vinwonders.com/2022/04/bai-bien-my-khe-da-nang-2.jpg",
    },
    {
        deleteAt: false,
        _id: 5,
        name: "Hon Ta,",
        province: "Can Tho",
        country: "Việt Nam",
        valueate: 10,
        __v: 0,
        image: "https://bantour.net/images/2017/07/du-lich-ben-ninh-kieu-can-tho-1.jpg",
    },
    {
        deleteAt: false,
        _id: 1398,
        name: "Bridge Temple",
        province: "Hội An",
        country: "Việt Nam",
        valueate: 10,
        __v: 0,
        image: "https://airbnb.cybersoft.edu.vn/public/temp/1660813512702_7.jpg",
    },
    {
        deleteAt: false,
        _id: 7,
        name: "Langbiang",
        province: "Ninh Thuan",
        country: "Việt Nam",
        valueate: 10,
        __v: 0,
        image: "https://airbnb.cybersoft.edu.vn/public/temp/1660814101648_12.jpg",
    },
    {
        deleteAt: false,
        _id: 8,
        name: "Mui Ne",
        province: "Vinh Long",
        country: "viet nam",
        valueate: 10,
        __v: 0,
        image: "https://airbnb.cybersoft.edu.vn/public/temp/1641022921454_tokyo-wallpapers-(8)-by-twalls.jpg",
    },
    {
        deleteAt: false,
        _id: 1351,
        name: "Ha Long Bay",
        province: "Quảng Ninh",
        country: "viet nam",
        valueate: 10,
        __v: 0,
        image: "https://image.kkday.com/v2/image/get/w_960%2Cc_fit%2Cq_55%2Ct_webp/s1.kkday.com/product_129620/20220519104059_FIN0y/png",
    },
    {
        deleteAt: false,
        _id: 4,
        name: "Hoan Kiem Lake",
        province: "Ha Noi",
        country: "66666",
        valueate: 9,
        __v: 0,
        image: "https://www.lasinfoniadelreyhotel.com/img/upload/west_lake.gif",
    },
    {
        deleteAt: false,
        _id: 2,
        name: "Cai Rang",
        province: "Tra Vinh",
        country: "VN",
        valueate: 9,
        __v: 0,
        image: "https://airbnb.cybersoft.edu.vn/public/temp/1641022845413_yokohama-wallpaper-(13)-by-twalls.jpg",
    },
];

export { nearPlaceList };
